### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by Calinou** [armory3d/armorpaint_unity#3]
This repository currently has no license attached. I'd suggest adding the [same license as ArmorPaint itself](https://github.com/armory3d/armorpaint/blob/master/LICENSE.md) just in case :slightly_smiling_face: 

See also https://github.com/armory3d/armorpaint_unreal/issues/2.

**Comment by luboslenco** [comment]
Fixed, also thanks. https://github.com/armory3d/armorpaint_unity/commit/dd9fda214518d0c3cd094d17da43e227c95a1ff1
